/*
 * This file is generated by jOOQ.
*/
package li.barlog.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Person implements Serializable {

    private static final long serialVersionUID = 1077785521;

    private final Long                   id;
    private final li.barlog.model.Person data;
    private final LocalDateTime          created;

    public Person(Person value) {
        this.id = value.id;
        this.data = value.data;
        this.created = value.created;
    }

    public Person(
        Long                   id,
        li.barlog.model.Person data,
        LocalDateTime          created
    ) {
        this.id = id;
        this.data = data;
        this.created = created;
    }

    public Long getId() {
        return this.id;
    }

    public li.barlog.model.Person getData() {
        return this.data;
    }

    public LocalDateTime getCreated() {
        return this.created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Person (");

        sb.append(id);
        sb.append(", ").append(data);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
