spring:
  main.banner-mode: "off"
  application.name: postgres-performance
  output.ansi.enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate

  jooq:
    sql-dialect: POSTGRES_9_5

logging:
  pattern:
    level: "%clr(%-5p)"
    console: "%date{yyyy.MM.dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN} %clr([%thread]){magenta} %clr(%logger{-1}){cyan}->%clr(%method){blue}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level.root: INFO
