version: '3'

services:
  postgres-json-config:
    build:
      context: ./postgres-config
    volumes:
      - config:/config

  postgres-json:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - config:/config
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  config:
