/*
 * This file is generated by jOOQ.
*/
package li.barlog.model.jooq;


import javax.annotation.Generated;

import li.barlog.model.jooq.tables.Person;
import li.barlog.model.jooq.tables.SchemaVersion;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.person</code>.
     */
    public static final Person PERSON = li.barlog.model.jooq.tables.Person.PERSON;

    /**
     * The table <code>public.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = li.barlog.model.jooq.tables.SchemaVersion.SCHEMA_VERSION;
}
